Repository eunaJ/LightHouseAI-front, pull requests merged in 2024-05, with the labels that each got.

#3 Feature/refreshapi/init - feature: axios 활용한 refresh 기능 추가
  src/components/RefreshApi.js
Labels: feature

#5 Feature/home/init - 홈페이지 기본 틀 구현 및 travelcard 틀 구현
  src/components/travel/TravelCard.css
  src/components/travel/TravelCard.js
  src/pages/Home.css
  src/pages/Home.js
Labels: feature

#7 Feature/login/init - 기본, 카카오, 네이버 로그인 기능 추가
  .gitignore
  src/App.js
  src/pages/user/KakaoRedirect.js
  src/pages/user/Login.css
  src/pages/user/Login.js
  src/pages/user/NaverRedirect.js
Labels: feature

#9 Feature/signup/init - 회원가입 기능 추가
  src/App.js
  src/pages/user/Signup.css
  src/pages/user/Signup.js
Labels: feature

#11 Feature/user/mypage/init - User Mypage 기능 추가 및 PrivateRoute 기능 추가
  src/App.js
  src/pages/PrivateRoute.js
  src/pages/user/MyPage.css
  src/pages/user/MyPage.js
Labels: feature

#13 Feature/user/myinfo/init - User MyPage 기능 추가 및 PrivateRoute의 isLogin 위치 수정
  src/App.js
  src/pages/PrivateRoute.js
  src/pages/user/MyInfo.css
  src/pages/user/MyInfo.js
Labels: refactor, feature

#15 Feature/board/boardlist/init - Board 기능 추가
  src/App.js
  src/pages/board/Board.css
  src/pages/board/Board.js
Labels: feature

#17 Feature/travel/search/init - Home 카테고리 수정 및 검색 기능 추가 및 마이페이지 버튼 추가
  src/pages/Home.css
  src/pages/Home.js
  src/pages/board/Board.js
  src/pages/user/MyPage.css
  src/pages/user/MyPage.js
Labels: refactor, feature

#19 feature: MyInfo페이지 구현
  src/pages/user/MyInfo.css
  src/pages/user/MyInfo.js
Labels: feature

#26 Feature/traveldetail/init - 내 여행지, 여행지 수정, 상세페이지 추가 및 필요없는 부분 삭제
  src/App.js
  src/components/travel/Travel.js
  src/components/travel/TravelCard.css
  src/components/travel/TravelCard.js
  src/pages/Home.js
  src/pages/travel/TravelDetail.css
  src/pages/travel/TravelDetail.js
  src/pages/travel/TravelModal.css
  src/pages/travel/TravelModal.js
  src/pages/travel/TravelModalCard.js
  src/pages/travel/TravelModalCardUpdate.js
  src/pages/travel/TravelRegister.js
  src/pages/travel/TravelUpdate.css
  src/pages/travel/TravelUpdate.js
  src/pages/user/MyPage.js
  src/pages/user/MyTravel.css
  src/pages/user/MyTravel.js
  src/pages/user/Signup.js
Labels: refactor, feature

#30 Refactor/user,travel - 불필요한 부분 삭제 및 오류 수정
  src/assets/img/background_img_03.png
  src/components/RefreshApi.js
  src/components/travel/Travel.js
  src/components/travel/TravelCard.css
  src/components/travel/TravelCard.js
  src/pages/Home.css
  src/pages/Home.js
  src/pages/travel/TravelDetail.css
  src/pages/travel/TravelDetail.js
  src/pages/travel/TravelModal.js
  src/pages/travel/TravelModalCard.css
  src/pages/travel/TravelModalCardUpdate.js
  src/pages/travel/TravelRegister.css
  src/pages/travel/TravelRegister.js
  src/pages/travel/TravelUpdate.css
  src/pages/travel/TravelUpdate.js
  src/pages/user/Login.js
  src/pages/user/MyInfo.js
  src/pages/user/MyPage.js
  src/pages/user/MyTravel.css
  src/pages/user/MyTravel.js
  src/pages/user/Signup.css
  src/pages/user/Signup.js
Labels: refactor, feature

#28 feature: 지역명 선택 후 지역에 있는 가게들만 가져오기
  package-lock.json
  package.json
  src/pages/travel/TravelModal.js
  src/pages/travel/TravelRegister.js
Labels: feature

#35 Refactor/user/delete/search - 디자인 수정 및 constituency_id 오류 수정 및 price null 오류 수정
  src/components/travel/Travel.js
  src/components/travel/TravelCard.css
  src/components/travel/TravelCard.js
  src/pages/Home.css
  src/pages/Home.js
  src/pages/travel/TravelModal.js
  src/pages/travel/TravelRegister.js
  src/pages/user/MyPage.css
  src/pages/user/MyPage.js
  src/pages/user/MyTravel.css
  src/pages/user/MyTravel.js
Labels: refactor

#23 Origin/feature/ai recommand
  .gitignore
  .idea/vcs.xml
  .idea/workspace.xml
  package-lock.json
  package.json
  src/App.js
  src/pages/AI/Card.css
  src/pages/AI/Card.js
  src/pages/AI/Recommand.css
  src/pages/AI/Recommand.js
  src/pages/AI/Sidebar.css
  src/pages/AI/Sidebar.js
  src/pages/Home.css
  src/pages/Home.js
Labels: feature
